version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.env:/var/www/.env
        environment:
            - APP_ENV=local
        networks:
            - internal

    nginx:
        image: nginx:alpine
        container_name: my-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - internal

    node:
        build:
            context: .
            dockerfile: Dockerfile.node
        image: my-laravel-node
        container_name: my-laravel-node
        ports:
            - "3000:3000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - internal

    db:
        image: mysql:8.0
        container_name: my-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "laravel_social"
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_PASS: "password"
            MYSQL_USER: "user"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - internal
        ports:
            - "3306:3306"

networks:
    internal:
        driver: bridge

volumes:
    dbdata:
        driver: local
